### ISSUE TITLE
Launch and connection

### ISSUE THREAD

**Issue by bulava92** [anyproto/any-sync-dockercompose#121]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I installed the program, but I don't understand how to connect and how to use it
log
[111.log](https://github.com/user-attachments/files/18279588/111.log)

### Expected Behavior

I tried different port options, etc.

```
AWS_ACCESS_KEY_ID=minio_access_key
AWS_SECRET_ACCESS_KEY=minio_secret_key
MINIO_BUCKET=minio-bucket
MINIO_PORT=9000
EXTERNAL_MINIO_PORT=${MINIO_PORT}
MINIO_WEB_PORT=9001
EXTERNAL_MINIO_WEB_PORT=${MINIO_WEB_PORT}

ANY_SYNC_NODE_VERSION=latest
ANY_SYNC_FILENODE_VERSION=latest
ANY_SYNC_COORDINATOR_VERSION=latest
ANY_SYNC_CONSENSUSNODE_VERSION=latest
ANY_SYNC_TOOLS_VERSION=latest

MONGO_VERSION=7.0.2
REDIS_VERSION=7.2.0-v6
MINIO_VERSION=RELEASE.2024-07-04T14-25-45Z

EXTERNAL_LISTEN_HOST="127.0.0.1:6775"
#EXTERNAL_LISTEN_HOSTS="192.168.1.2 10.0.0.2"

ANY_SYNC_NODE_1_HOST=any-sync-node-1
ANY_SYNC_NODE_1_PORT=1001
ANY_SYNC_NODE_1_ADDRESSES=${ANY_SYNC_NODE_1_HOST}:${ANY_SYNC_NODE_1_PORT}
ANY_SYNC_NODE_1_QUIC_PORT=1011
ANY_SYNC_NODE_1_QUIC_ADDRESSES=${ANY_SYNC_NODE_1_HOST}:${ANY_SYNC_NODE_1_QUIC_PORT}
ANY_SYNC_NODE_1_API_SERVER_ADDR=127.0.0.1:8081
ANY_SYNC_NODE_1_METRIC_ADDR=127.0.0.1:8001

ANY_SYNC_NODE_2_HOST=any-sync-node-2
ANY_SYNC_NODE_2_PORT=1002
ANY_SYNC_NODE_2_ADDRESSES=${ANY_SYNC_NODE_2_HOST}:${ANY_SYNC_NODE_2_PORT}
ANY_SYNC_NODE_2_QUIC_PORT=1012
ANY_SYNC_NODE_2_QUIC_ADDRESSES=${ANY_SYNC_NODE_2_HOST}:${ANY_SYNC_NODE_2_QUIC_PORT}
ANY_SYNC_NODE_2_API_SERVER_ADDR=127.0.0.1:8082
ANY_SYNC_NODE_2_METRIC_ADDR=127.0.0.1:8002

ANY_SYNC_NODE_3_HOST=any-sync-node-3
ANY_SYNC_NODE_3_PORT=1003
ANY_SYNC_NODE_3_ADDRESSES=${ANY_SYNC_NODE_3_HOST}:${ANY_SYNC_NODE_3_PORT}
ANY_SYNC_NODE_3_QUIC_PORT=1013
ANY_SYNC_NODE_3_QUIC_ADDRESSES=${ANY_SYNC_NODE_3_HOST}:${ANY_SYNC_NODE_3_QUIC_PORT}
ANY_SYNC_NODE_3_API_SERVER_ADDR=127.0.0.1:8083
ANY_SYNC_NODE_3_METRIC_ADDR=127.0.0.1:8003

ANY_SYNC_COORDINATOR_HOST=any-sync-coordinator
ANY_SYNC_COORDINATOR_PORT=1004
ANY_SYNC_COORDINATOR_ADDRESSES=${ANY_SYNC_COORDINATOR_HOST}:${ANY_SYNC_COORDINATOR_PORT}
ANY_SYNC_COORDINATOR_QUIC_PORT=1014
ANY_SYNC_COORDINATOR_QUIC_ADDRESSES=${ANY_SYNC_COORDINATOR_HOST}:${ANY_SYNC_COORDINATOR_QUIC_PORT}
ANY_SYNC_COORDINATOR_METRIC_ADDR=127.0.0.1:8004
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SPACE_MEMBERS_READ=1000
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SPACE_MEMBERS_WRITE=1000
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SHARED_SPACES_LIMIT=1000

ANY_SYNC_FILENODE_HOST=any-sync-filenode
ANY_SYNC_FILENODE_PORT=1005
ANY_SYNC_FILENODE_ADDRESSES=${ANY_SYNC_FILENODE_HOST}:${ANY_SYNC_FILENODE_PORT}
ANY_SYNC_FILENODE_QUIC_PORT=1015
ANY_SYNC_FILENODE_QUIC_ADDRESSES=${ANY_SYNC_FILENODE_HOST}:${ANY_SYNC_FILENODE_QUIC_PORT}
ANY_SYNC_FILENODE_METRIC_ADDR=127.0.0.1:8005
ANY_SYNC_FILENODE_DEFAULT_LIMIT=1099511627776

ANY_SYNC_CONSENSUSNODE_HOST=any-sync-consensusnode
ANY_SYNC_CONSENSUSNODE_PORT=1006
ANY_SYNC_CONSENSUSNODE_ADDRESSES=${ANY_SYNC_CONSENSUSNODE_HOST}:${ANY_SYNC_CONSENSUSNODE_PORT}
ANY_SYNC_CONSENSUSNODE_QUIC_PORT=1016
ANY_SYNC_CONSENSUSNODE_QUIC_ADDRESSES=${ANY_SYNC_CONSENSUSNODE_HOST}:${ANY_SYNC_CONSENSUSNODE_QUIC_PORT}
ANY_SYNC_CONSENSUSNODE_METRIC_ADDR=127.0.0.1:8006

MONGO_1_PORT=27001
MONGO_CONNECT=mongodb://mongo-1:${MONGO_1_PORT}
MONGO_REPLICA_SET=rs0
MONGO_URL=${MONGO_CONNECT}/?replicaSet=${MONGO_REPLICA_SET}

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_URL="redis://${REDIS_HOST}:${REDIS_PORT}?dial_timeout=3&read_timeout=6s"
REDIS_MAXMEMORY=256mb

STORAGE_DIR="./storage"

ANY_SYNC_DAEMONS_MEMORY_LIMIT=500M
```

### Steps To Reproduce

-

### Environment

```markdown
ubuntu 24
```

**Comment by bulava92** [comment]
How to install on ubuntu24 and how to connect the computer and phone to the server? I've been trying to run it all day, but it doesn't work. There are not enough detailed instructions

**Comment by bulava92** [comment]
And also I don't understand how to connect my storage s3

There are only settings for minio, and where to write S3_ENDPOINT or S3_REGION?

AWS_ACCESS_KEY_ID=minio_access_key
AWS_SECRET_ACCESS_KEY=minio_secret_key
MINIO_BUCKET=minio-bucket
MINIO_PORT=9000
EXTERNAL_MINIO_PORT=${MINIO_PORT}
MINIO_WEB_PORT=9001
EXTERNAL_MINIO_WEB_PORT=${MINIO_WEB_PORT}

**Comment by bulava92** [comment]
I tried to specify the s3 configuration in different ways, but it doesn't work. How can I not run Minio so that the work goes through my s3 bucket?

`root@qrzauyqghy:~/any-sync-dockercompose# make start
docker buildx build --load --tag generateconfig-env --file Dockerfile-generateconfig-env .
[+] Building 3.2s (12/12) FINISHED                                                            docker-container:brave_jang
 => [internal] load build definition from Dockerfile-generateconfig-env                                              0.0s
 => => transferring dockerfile: 286B                                                                                 0.0s
 => resolve image config for docker-image://docker.io/docker/dockerfile:1                                            1.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:93bfd3b68c109427185cd78b4779fc82b484b0b7618e36d0f104  0.0s
 => => resolve docker.io/docker/dockerfile:1@sha256:93bfd3b68c109427185cd78b4779fc82b484b0b7618e36d0f104d4d801e66d2  0.0s
 => [internal] load metadata for docker.io/library/python:3.11-alpine                                                0.5s
 => [internal] load .dockerignore                                                                                    0.0s
 => => transferring context: 2B                                                                                      0.0s
 => [1/4] FROM docker.io/library/python:3.11-alpine@sha256:bc84eb94541f34a0e98535b130ea556ae85f6a431fdb3095762772ee  0.0s
 => => resolve docker.io/library/python:3.11-alpine@sha256:bc84eb94541f34a0e98535b130ea556ae85f6a431fdb3095762772ee  0.0s
 => [internal] load build context                                                                                    0.0s
 => => transferring context: 104B                                                                                    0.0s
 => CACHED [2/4] WORKDIR /code                                                                                       0.0s
 => CACHED [3/4] COPY docker-generateconfig/env-requirements.txt requirements.txt                                    0.0s
 => CACHED [4/4] RUN pip install -r requirements.txt                                                                 0.0s
 => exporting to docker image format                                                                                 0.9s
 => => exporting layers                                                                                              0.0s
 => => exporting manifest sha256:ef324bfd791b082d104b5e6b0b38b5f3a1a1fd8b04b7e2a2c7253118e91dc3a6                    0.0s
 => => exporting config sha256:eb8d1e645a97acaaf0ee38eccd3f39e91d06f27607a01a0ecfc99363caca5c19                      0.0s
 => => sending tarball                                                                                               0.9s
 => importing to docker                                                                                              0.0s
docker run --rm \
        --volume /root/any-sync-dockercompose/:/code/ \
        generateconfig-env
docker-compose up --detach --remove-orphans --quiet-pull
Starting any-sync-dockercompose_generateconfig-anyconf_1 ... 
Recreating 1300db0ea5cd_any-sync-dockercompose_minio_1   ... 
Starting any-sync-dockercompose_generateconfig-anyconf_1 ... done
ERROR: for 1300db0ea5cd_any-sync-dockercompose_minio_1  'ContainerConfig'
Starting any-sync-dockercompose_generateconfig-processing_1 ... done
Starting any-sync-dockercompose_redis_1                     ... done
Starting any-sync-dockercompose_mongo-1_1                   ... done
Starting any-sync-dockercompose_any-sync-coordinator_bootstrap_1 ... done
Starting any-sync-dockercompose_any-sync-coordinator_1           ... done
Starting any-sync-dockercompose_any-sync-node-2_1                ... done
Starting any-sync-dockercompose_any-sync-node-1_1                ... done
Starting any-sync-dockercompose_any-sync-node-3_1                ... done
Starting any-sync-dockercompose_any-sync-consensusnode_1         ... done

ERROR: for minio  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[152584] Failed to execute script docker-compose
make: *** [Makefile:24: start] Error 255`

**Comment by bulava92** [comment]
I specified the parameters in/root/any-sync-dockercompose/docker-generateconfig/etc/filenode.yml
s3Store:
    bucket: %MINIO_BUCKET%
    indexBucket: %MINIO_BUCKET%
    maxThreads: 16
    profile: default
    region: us-east-1
    endpoint: http://minio:%MINIO_PORT%
    forcePathStyle: true # 'true' for self-hosted S3 Object Storage
    
    
And also in /root/any-sync-dockercompose/.env.override password and login s3 but I keep getting an error

```
root@qrzauyqghy:~/any-sync-dockercompose# make start
docker buildx build --load --tag generateconfig-env --file Dockerfile-generateconfig-env .
[+] Building 3.3s (12/12) FINISHED                                                            docker-container:brave_jang
 => [internal] load build definition from Dockerfile-generateconfig-env                                              0.0s
 => => transferring dockerfile: 286B                                                                                 0.0s
 => resolve image config for docker-image://docker.io/docker/dockerfile:1                                            1.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:93bfd3b68c109427185cd78b4779fc82b484b0b7618e36d0f104  0.0s
 => => resolve docker.io/docker/dockerfile:1@sha256:93bfd3b68c109427185cd78b4779fc82b484b0b7618e36d0f104d4d801e66d2  0.0s
 => [internal] load metadata for docker.io/library/python:3.11-alpine                                                0.4s
 => [internal] load .dockerignore                                                                                    0.0s
 => => transferring context: 2B                                                                                      0.0s
 => [1/4] FROM docker.io/library/python:3.11-alpine@sha256:bc84eb94541f34a0e98535b130ea556ae85f6a431fdb3095762772ee  0.0s
 => => resolve docker.io/library/python:3.11-alpine@sha256:bc84eb94541f34a0e98535b130ea556ae85f6a431fdb3095762772ee  0.0s
 => [internal] load build context                                                                                    0.0s
 => => transferring context: 104B                                                                                    0.0s
 => CACHED [2/4] WORKDIR /code                                                                                       0.0s
 => CACHED [3/4] COPY docker-generateconfig/env-requirements.txt requirements.txt                                    0.0s
 => CACHED [4/4] RUN pip install -r requirements.txt                                                                 0.0s
 => exporting to docker image format                                                                                 1.2s
 => => exporting layers                                                                                              0.0s
 => => exporting manifest sha256:ef324bfd791b082d104b5e6b0b38b5f3a1a1fd8b04b7e2a2c7253118e91dc3a6                    0.0s
 => => exporting config sha256:eb8d1e645a97acaaf0ee38eccd3f39e91d06f27607a01a0ecfc99363caca5c19                      0.0s
 => => sending tarball                                                                                               1.2s
 => importing to docker                                                                                              0.0s
docker run --rm \
        --volume /root/any-sync-dockercompose/:/code/ \
        generateconfig-env
docker-compose up --detach --remove-orphans --quiet-pull
Recreating 1300db0ea5cd_any-sync-dockercompose_minio_1 ... 
Starting any-sync-dockercompose_generateconfig-anyconf_1 ... 

Starting any-sync-dockercompose_generateconfig-anyconf_1 ... done
Starting any-sync-dockercompose_generateconfig-processing_1 ... done
Starting any-sync-dockercompose_redis_1                     ... done
Starting any-sync-dockercompose_mongo-1_1                   ... done
Starting any-sync-dockercompose_any-sync-coordinator_bootstrap_1 ... done
Starting any-sync-dockercompose_any-sync-coordinator_1           ... done
Starting any-sync-dockercompose_any-sync-node-2_1                ... done
Starting any-sync-dockercompose_any-sync-consensusnode_1         ... done
Starting any-sync-dockercompose_any-sync-node-1_1                ... done
Starting any-sync-dockercompose_any-sync-node-3_1                ... done

ERROR: for minio  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[236524] Failed to execute script docker-compose
make: *** [Makefile:24: start] Error 255
```

**Comment by teacup418** [comment]
how did you fix it? I have problem with s3 config, could you share your steps?
